/// The SketchIt word list: common, concrete, drawable words - animals,
/// food, objects, people, places, actions. Curated (not dictionary
/// derived) because "walycoat" is no fun to draw.
library;

const List<String> sketchWords = [
  // animals
  'dog', 'cat', 'bird', 'fish', 'bear', 'lion', 'tiger', 'horse', 'cow',
  'pig', 'sheep', 'goat', 'duck', 'chicken', 'rooster', 'owl', 'eagle',
  'penguin', 'dolphin', 'shark', 'whale', 'octopus', 'crab', 'turtle',
  'frog', 'snake', 'rabbit', 'mouse', 'rat', 'deer', 'fox', 'wolf',
  'monkey', 'gorilla', 'elephant', 'giraffe', 'zebra', 'camel', 'kangaroo',
  'koala', 'panda', 'bat', 'bee', 'ant', 'spider', 'snail', 'worm',
  'butterfly', 'mosquito', 'dinosaur', 'dragon', 'unicorn', 'moose',
  'seal', 'lobster', 'parrot', 'swan', 'peacock', 'hedgehog', 'squirrel',
  'raccoon', 'hamster', 'donkey', 'goose', 'turkey', 'kitten', 'puppy',
  // food + drink
  'pizza', 'burger', 'taco', 'sushi', 'pasta', 'salad', 'soup', 'bread',
  'cheese', 'egg', 'bacon', 'milk', 'cake', 'cookie', 'candy', 'chocolate',
  'sundae', 'pie', 'donut', 'pancake', 'waffle', 'cereal', 'popcorn',
  'pretzel', 'sandwich', 'hotdog', 'ketchup', 'lemon', 'lime', 'apple',
  'banana', 'orange', 'grape', 'cherry', 'strawberry', 'watermelon',
  'pineapple', 'coconut', 'mango', 'peach', 'pear', 'plum', 'potato',
  'tomato', 'onion', 'garlic', 'carrot', 'corn', 'broccoli', 'mushroom',
  'pumpkin', 'pepper', 'honey', 'toast', 'coffee', 'tea', 'juice', 'soda',
  'beer', 'wine', 'chips', 'fries', 'noodles', 'rice', 'dumpling',
  'kebab', 'burrito', 'nacho', 'bagel', 'croissant', 'muffin', 'sausage',
  // objects + household
  'chair', 'table', 'desk', 'bed', 'sofa', 'lamp', 'candle', 'clock',
  'mirror', 'window', 'door', 'roof', 'key', 'lock', 'phone', 'camera',
  'radio', 'laptop', 'keyboard', 'tablet', 'book', 'pen', 'pencil',
  'paper', 'scissors', 'glue', 'tape', 'ruler', 'eraser', 'backpack',
  'wallet', 'glasses', 'watch', 'ring', 'necklace', 'hat', 'cap', 'shoe',
  'boot', 'sock', 'glove', 'scarf', 'coat', 'jacket', 'shirt', 'pants',
  'dress', 'skirt', 'tie', 'belt', 'umbrella', 'suitcase', 'towel',
  'blanket', 'pillow', 'toothbrush', 'soap', 'shampoo', 'comb', 'brush',
  'bucket', 'broom', 'mop', 'hammer', 'nail', 'wrench', 'saw', 'drill',
  'ladder', 'rope', 'chain', 'anchor', 'wheel', 'engine', 'battery',
  'plug', 'wire', 'magnet', 'telescope', 'compass', 'map', 'globe',
  'flag', 'crown', 'sword', 'shield', 'helmet', 'arrow', 'bow', 'cannon',
  'rocket', 'balloon', 'kite', 'gift', 'envelope', 'letter', 'stamp',
  'ticket', 'calendar', 'puzzle', 'dice', 'card', 'doll', 'mask',
  'trophy', 'medal', 'oven', 'fridge', 'stove', 'sink', 'bathtub',
  'shower', 'toilet', 'pill', 'bandage',
  // people + creatures
  'baby', 'child', 'man', 'woman', 'boy', 'girl', 'king', 'queen',
  'prince', 'princess', 'knight', 'pirate', 'clown', 'chef', 'doctor',
  'nurse', 'teacher', 'farmer', 'police', 'judge', 'soldier', 'pilot',
  'astronaut', 'sailor', 'wizard', 'witch', 'ghost', 'skeleton', 'mummy',
  'robot', 'alien', 'monster', 'angel', 'devil', 'giant', 'dwarf', 'elf',
  'fairy', 'superhero', 'singer', 'dancer', 'artist', 'musician',
  'magician', 'boxer', 'swimmer', 'runner', 'fisherman', 'baker',
  'waiter', 'painter', 'spy', 'thief', 'ninja', 'samurai', 'cowboy',
  'viking', 'mermaid', 'ballerina', 'wrestler', 'zombie', 'vampire',
  'werewolf', 'troll', 'goblin', 'gnome', 'santa',
  // places + nature
  'house', 'school', 'church', 'bank', 'hospital', 'library', 'museum',
  'theater', 'cinema', 'stadium', 'airport', 'station', 'factory',
  'restaurant', 'hotel', 'shop', 'market', 'garden', 'garage', 'pool',
  'playground', 'zoo', 'farm', 'city', 'village', 'castle', 'tent',
  'igloo', 'cabin', 'barn', 'lighthouse', 'fountain', 'statue', 'pyramid',
  'cave', 'mountain', 'volcano', 'island', 'beach', 'desert', 'forest',
  'river', 'lake', 'ocean', 'waterfall', 'rainbow', 'cloud', 'rain',
  'snow', 'storm', 'lightning', 'tornado', 'ice', 'fire', 'smoke', 'moon',
  'sun', 'star', 'planet', 'sky', 'flower', 'tree', 'leaf', 'grass',
  'cactus', 'rose', 'tulip', 'daisy', 'sunflower', 'bridge', 'tunnel',
  'road', 'sign', 'fence', 'gate', 'well', 'tower',
  // vehicles
  'airplane', 'helicopter', 'boat', 'ship', 'train', 'bus', 'car',
  'truck', 'bike', 'motorcycle', 'skateboard', 'scooter', 'wagon',
  'tractor', 'submarine', 'parachute',
  // actions + feelings + music
  'run', 'jump', 'swim', 'dive', 'climb', 'fly', 'crawl', 'dance', 'sing',
  'draw', 'paint', 'write', 'read', 'sleep', 'eat', 'drink', 'cook',
  'bake', 'cut', 'sew', 'dig', 'sweep', 'wash', 'ski', 'skate', 'surf',
  'sail', 'golf', 'tennis', 'soccer', 'football', 'baseball',
  'basketball', 'hockey', 'boxing', 'karate', 'yoga', 'juggle', 'laugh',
  'cry', 'smile', 'frown', 'sneeze', 'cough', 'yawn', 'wave', 'clap',
  'kick', 'punch', 'throw', 'catch', 'lift', 'push', 'pull', 'carry',
  'hug', 'kiss', 'shout', 'whistle', 'bark', 'meow', 'roar', 'guitar',
  'piano', 'violin', 'drum', 'flute', 'trumpet', 'saxophone', 'harp',
  'bell', 'microphone', 'heart', 'love', 'angry', 'happy', 'sad', 'tired',
  'hungry', 'cold', 'hot', 'wet', 'dry', 'money', 'coin', 'diamond',
  'treasure', 'fireworks', 'party', 'birthday', 'mailbox', 'package',
  'trampoline', 'barbecue', 'campfire', 'swing', 'slide', 'seesaw',
  'hammock', 'wheelchair', 'crutch', 'dumbbell',
];
